### ISSUE TITLE
Моторы осей X, Y не работают

### ISSUE THREAD

**Issue by qulet** [akv47/DrawBot_nano#1]
Я скомпилировал код DrawBot_nano, загрузил его на плату Arduino Uno cnc schiled V3. LaserGRBL подключается к прошивке GRBL0.9J, но серводвигатели X, Y M03 S100 тоже не работают.

Тот же хардвер, но прошивка GRBL 1.1, двигатели и сервопривод работают.
![Scara_config](https://user-images.githubusercontent.com/30979927/163847967-e7609f2e-6366-4b2b-a243-1a123d9ecc1b.png)
![Grbllaser](https://user-images.githubusercontent.com/30979927/163848128-bc7175a5-812a-4192-84bd-f727243ac3bb.png)
![IMG20220418193205](https://user-images.githubusercontent.com/30979927/163848660-0905d01f-faaf-4b9e-9613-472b4803e4d1.jpg)

**Comment by qulet** [comment]
Я загрузил эту прошивку на Arduino nano и cnc schiled V4. Кажется, все работает. Есть только проблема с калибровкой. Рисует квадрат 100x100 Стороны Y прямые, а стороны X радиусы. Плечи имеют длину ровно 200 мм, все как показано на прилагаемом калибровочном чертеже. Проверял разные настройки калибровки, потратил на это около 3х часов. Без желаемого эффекта. высылаю фото. Надпись FRANEK выполнена на прошивке https://www.thingiverse.com/MG-dream-technology. Неудачный прямоугольник на GRBLNano.
![rysunek](https://user-images.githubusercontent.com/30979927/164992040-adba9702-d2e8-4cd4-83ed-5a2abb513ce2.jpg)

**Comment by akv47** [comment]
Нужно откалибровать. Модель растягивается, если неправильно откалиброван рисовальщик. Калибруй командой $M, пока линии по осям X и У не станут прямыми и перпендикулярными между собой. Можешь попробовать в ручную  поменять значения углов psi и theta в конфигурации GRBL, после каждой замены и сохранения нужен аппаратный сброс. Важно правильно установить ручку перед калибровкой, линии изгиба сверного листа A4 проходят через кончик ручки и линию платформы, плечо, которое ближе к платформе, параллельно линии платформы, а угол листа должен совпадать с центром подшипника соединения плеч. Если калибровал так, как показано на первом фото, то это не правильно. 
Правильно так ![Калибровка](https://github.com/akv47/DrawBot_nano/blob/main/pic/calibration.jpg)

**Comment by qulet** [comment]
Спасибо за ваш ответ. Мне не удалось правильно откалибровать GRBL. Вернулся к исходной drawbot-V6_English.hex. Там я смог правильно откалибровать загрузочный ботинок.
